### ISSUE TITLE
Organize I/Os in params json 

### ISSUE THREAD

**Issue by arielleleon** [AllenNeuralDynamics/aind-ophys-oasis-event-detection#3]
Oasis event detection is storing input parameters and outputs in the params json. We need to make sure we are only keeping relevant metrics and that they are stored in the correct locations (inputs in processing and outputs in h5).

**Comment by j-friedrich** [comment]
Done! The corresponding [PR](https://github.com/AllenNeuralDynamics/aind-ophys-oasis-event-detection/pull/4) has been merged.
